version: '3.8'
services:
  link_crawler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: link_crawler
    environment:
      - AWS_SHARED_CREDENTIALS_FILE=/code/.aws/credentials
    restart: "no"
    command: ["python", "/code/crawling/link_crawling.py"]
    volumes:
      - ./crawling:/code/crawling
      - ./logs:/code/logs
      - ~/.aws:/code/.aws:ro

  post_crawler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: post_crawler
    environment:
      - AWS_SHARED_CREDENTIALS_FILE=/code/.aws/credentials
    restart: "no"
    command: ["python", "/code/crawling/post_crawling.py"]
    volumes:
      - ./crawling:/code/crawling
      - ./logs:/code/logs
      - ~/.aws:/code/.aws:ro

  text_crawler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: text_crawler
    environment:
      - AWS_SHARED_CREDENTIALS_FILE=/code/.aws/credentials
    restart: "no"
    command: ["python", "/code/crawling/text_preprocess.py"]
    volumes:
      - ./crawling:/code/crawling
      - ./extract:/code/extract
      - ./logs:/code/logs
      - ~/.aws:/code/.aws:ro

  jumpit_crawler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jumpit_crawler
    environment:
      - AWS_SHARED_CREDENTIALS_FILE=/code/.aws/credentials
    restart: "no"
    command: ["python", "/code/crawling/jumpit_crawling.py"]
    volumes:
      - ./crawling:/code/crawling
      - ./logs:/code/logs
      - ~/.aws:/code/.aws:ro

  wanted_crawler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wanted_crawler
    environment:
      - AWS_SHARED_CREDENTIALS_FILE=/code/.aws/credentials
    restart: "no"
    command: ["python", "/code/crawling/wanted_crawling.py"]
    volumes:
      - ./crawling:/code/crawling
      - ./logs:/code/logs
      - ~/.aws:/code/.aws:ro

  incruit_crawler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: incruit_crawler
    environment:
      - AWS_SHARED_CREDENTIALS_FILE=/code/.aws/credentials
    restart: "no"
    command: ["python", "/code/crawling/incruit_crawling.py"]
    volumes:
      - ./crawling:/code/crawling
      - ./logs:/code/logs
      - ~/.aws:/code/.aws:ro

  jobkorea_crawler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jobkorea_crawler
    environment:
      - AWS_SHARED_CREDENTIALS_FILE=/code/.aws/credentials
    restart: "no"
    command: ["python", "/code/crawling/jobkorea_crawling.py"]
    volumes:
      - ./crawling:/code/crawling
      - ./logs:/code/logs
      - ~/.aws:/code/.aws:ro

  saramin_crawler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: saramin_crawler
    environment:
      - AWS_SHARED_CREDENTIALS_FILE=/code/.aws/credentials
    restart: "no"
    command: ["python", "/code/crawling/saramin_crawling.py"]
    volumes:
      - ./crawling:/code/crawling
      - ./logs:/code/logs
      - ~/.aws:/code/.aws:ro
