version: "3.8"

services:
  frontend:
    image: public.ecr.aws/u5b2p7i3/job_scanner/app:frontend-latest  # ECR에서 푸시된 프론트엔드 이미지
    ports:
      - "80:80"  # EC2의 80번 포트로 접근 가능
    networks:
      - app-network  # frontend와 backend 서비스가 동일한 네트워크에서 실행되도록 설정

  backend:
    image: public.ecr.aws/u5b2p7i3/job_scanner/app:backend-latest  # ECR에서 푸시된 백엔드 이미지
    ports:
      - "8972:8972"  # EC2의 8972번 포트로 접근 가능
    networks:
      - app-network  # frontend와 backend 서비스가 동일한 네트워크에서 실행되도록 설정

networks:
  app-network:
    driver: bridge  # 기본 브리지 네트워크를 사용하여 서비스 간 통신이 가능하도록 설정
