version: '3.8'
services:
  link_crawler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: link_crawler
    environment:
      - AWS_SHARED_CREDENTIALS_FILE=/code/.aws/credentials
    restart: "no"
    command: ["python", "/code/crwaling/link_crawling.py"]
    volumes:
      - ./crwaling:/code/crwaling
      - ./logs:/code/logs
      - ~/.aws:/code/.aws:ro

  post_crawler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: post_crawler
    environment:
      - AWS_SHARED_CREDENTIALS_FILE=/code/.aws/credentials
    restart: "no"
    command: ["python", "/code/crwaling/post_crawling.py"]
    volumes:
      - ./crwaling:/code/crwaling
      - ./logs:/code/logs
      - ~/.aws:/code/.aws:ro

  text_crawler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: text_crawler
    environment:
      - AWS_SHARED_CREDENTIALS_FILE=/code/.aws/credentials
    restart: "no"
    command: ["python", "/code/crwaling/text_preprocess.py"]
    volumes:
      - ./crwaling:/code/crwaling
      - ./extract:/code/extract
      - ./logs:/code/logs
      - ~/.aws:/code/.aws:ro
