version: '3.8'

services:
  airflow:
    build:
      context: ./airflow
      dockerfile: Dockerfile-airflow
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: sqlite:////usr/local/airflow/airflow.db

  spark-master:
    build:
      context: ./spark
      dockerfile: Dockerfile-spark
    ports:
      - "7077:7077"
      - "4040:4040"
    environment:
      SPARK_MODE: master

  spark-worker:
    build:
      context: ./spark
      dockerfile: Dockerfile-spark
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077

