spring:
  application:
    name: jobscanner

  datasource:
    url: jdbc:mysql://t2rds.cfa60ymesotv.ap-northeast-2.rds.amazonaws.com:3306/swtestdb
    username: admin
    password: dltkddn1
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 150  # 최대 연결 수 (필요에 따라 조정)


  jpa:
    hibernate:
      ddl-auto: create  # 자동 스키마 생성 설정 (필요에 따라 조정) update: 기존 데이터 테이블 유지 변경점만 추가/ create: 애플리케이션 실행시 마다 테이블 삭제 재생성
    properties:
      hibernate:
        #show-sql: true  # SQL 쿼리 로그 표시 system.out 으로
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
#  security:
#    oauth2:
#      client:
#        registration:
#          naver:
#            client-id: tmvihhfzDh1QXcBigMWY
#            client-secret: 9hGpy3j8Uk
#            scope: profile, email
#            redirect-uri: http://43.202.114.11:8973/login/oauth2/code/naver
#            authorization-grant-type: authorization_code
#            client-name: Naver
#          kakao:
#            client-id: 88e63a16f05be054e9bdbac3bcdb410c
#            client-secret: ppFHDMdYCxAES3i8YfjNZXHWaj5El2Sd
#            scope: profile_nickname,account_email
#            redirect-uri: http://43.202.114.11:8973/login/oauth2/code/kakao
#            authorization-grant-type: authorization_code
#            client-authentication-method: POST
#            client-name: Kakao
#        provider:
#          naver:
#            authorization-uri: https://nid.naver.com/oauth2.0/authorize
#            token-uri: https://nid.naver.com/oauth2.0/token
#            user-info-uri: https://openapi.naver.com/v1/nid/me
#          kakao:
#            authorization-uri: https://kauth.kakao.com/oauth2/authorize
#            token-uri: https://kauth.kakao.com/oauth2/token
#            user-info-uri: https://kapi.kakao.com/v2/user/me


logging:
  level:
   org.hibernate.SQL: debug   # SQL 쿼리 로그 표시 logger로 
   org.hibernate.type.descriptor.sql: TRACE  # 파라미터 로그를 출력함 

# 서버 포트 변경 (추가 부분)
server:
  port: 8973  # Spring Boot 애플리케이션의 포트를 8973로 변경, 로컬에서는 localhost:8973 도커로 실행시 ????:8973 내부아이피가 됨.

