spring:
  application:
    name: jobscanner

  datasource:
    url: jdbc:mysql://t2rds.cfa60ymesotv.ap-northeast-2.rds.amazonaws.com:3306/service
    username: admin
    password: dltkddn1
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 150  # 최대 연결 수 (필요에 따라 조정)


  jpa:
    hibernate:
      ddl-auto: update  # 자동 스키마 생성 설정 (필요에 따라 조정) update: 기존 데이터 테이블 유지 변경점만 추가/ create: 애플리케이션 실행시 마다 테이블 삭제 재생성
    properties:
      hibernate:
        #show-sql: true  # SQL 쿼리 로그 표시 system.out 으로
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

logging:
  level:
   org.hibernate.SQL: debug   # SQL 쿼리 로그 표시 logger로 
   org.hibernate.type.descriptor.sql: TRACE  # 파라미터 로그를 출력함 

# 서버 포트 변경 (추가 부분)
server:
  port: 8972  # Spring Boot 애플리케이션의 포트를 8972로 변경
