name: CI/CD for Airflow and Spark

on:
  push:
    branches:
      - dev/crawling/saramin

jobs:
  build-and-push:
    name: Build and Push Docker Images to AWS ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      # AWS 자격 증명 구성
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      # ECR 로그인 # ECR 퍼블릭은 us-east-1리전만 동작 프라이빗변경 필요
      - name: Log in to Amazon ECR
        id: login-ecr
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/u5b2p7i3

      # docker images build or ECR push
      - name: Build and Push Airflow Image
        run: |
          docker build -t public.ecr.aws/u5b2p7i3/job_scanner/test_repo:airflow-latest -f ./airflow/Dockerfile-airflow .
          docker push public.ecr.aws/u5b2p7i3/job_scanner/test_repo:airflow-latest

      - name: Build and Push Spark Image
        run: |
          docker build -t public.ecr.aws/u5b2p7i3/job_scanner/test_repo:spark-latest -f ./spark/Dockerfile-spark .
          docker push public.ecr.aws/u5b2p7i3/job_scanner/test_repo:spark-latest

  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        run: |
          ssh -i ${{ secrets.EC2_PRIVATE_KEY }} ubuntu@${{ secrets.EC2_PUBLIC_IP }} << EOF
            docker pull public.ecr.aws/u5b2p7i3/job_scanner/test_repo:airflow-latest
            docker pull public.ecr.aws/u5b2p7i3/job_scanner/test_repo:spark-latest

            mkdir -p ~/deploy
            echo "
            version: '3.8'
            services:
              airflow:
                image: public.ecr.aws/u5b2p7i3/job_scanner/test_repo:airflow-latest
                ports:
                  - '8080:8080'

              spark-master:
                image: public.ecr.aws/u5b2p7i3/job_scanner/test_repo:spark-latest
                ports:
                  - '7077:7077'
                  - '4040:4040'
            " > ~/deploy/docker-compose.yaml

            docker-compose -f ~/deploy/docker-compose.yaml up -d
          EOF
